name: Deploy to Staging

on:
  push:
    branches:
      - master-production
 
jobs:
  deploy:
    # Do not deploy in the main repository, only in user project
    if: github.repository_owner != 'fastapi'
    runs-on:
      - self-hosted
      - staging
    env:
      ENVIRONMENT: staging
      DOMAIN: sorikama.com
      STACK_NAME: sorikama-staging
      DOCKER_IMAGE_FRONTEND: SorikamaHub/sorikama-frontend-staging
      TAG-latest: latest
      # SECRET_KEY: ${{ secrets.SECRET_KEY }}
      # FIRST_SUPERUSER: ${{ secrets.FIRST_SUPERUSER }
      # FIRST_SUPERUSER_PASSWORD: ${{ secrets.FIRST_SUPERUSER_PASSWORD }}
      # SMTP_HOST: ${{ secrets.SMTP_HOST }}
      # SMTP_USER: ${{ secrets.SMTP_USER }}
      # SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      # EMAILS_FROM_EMAIL: ${{ secrets.EMAILS_FROM_EMAIL }}
      # POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      # SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - run: docker compose -f docker-compose.yml --project-name sorikama-staging build --no-cache
      - run: docker compose -f docker-compose.yml --project-name sorikama-staging up -d
